services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quizza_api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: quizza_mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: quizza
        MYSQL_USER: quizza
        MYSQL_PASSWORD: quizza
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
